# Generated by Django 3.2.6 on 2021-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_media', models.FileField(upload_to='post/files', verbose_name='media file')),
                ('type_choice', models.SmallIntegerField(choices=[(0, 'image'), (1, 'Video')], verbose_name='media')),
            ],
            options={
                'verbose_name': 'PostMedia',
                'verbose_name_plural': 'PostMedia',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
